config/routes.rb
Rails.application.routes.draw do

  mount_point = Hubbubbly::Engine.config.mount_at

  scope(:path => mount_point) do
    resources :clippings, :only => [:show, :index], :path_prefix => mount_point
    resources :events, :only => [:show,:index], :path_prefix => mount_point
    resources :related_resources, :only => [:show, :index], :path_prefix => mount_point

    namespace :manage, :path_prefix => mount_point do
      resources :clippings do
        member do
          get 'import'
        end
      end
      resources :calendars do
        member do
          get 'import'
        end
      end
      resources :related_resources
      resources :sources do
        member do
          get 'import'
        end
      end
      resources :events, :only => [:new, :create, :update, :destroy]
    end
  end
end

app/models/calendar.rb
require 'open-uri'
class Calendar < ActiveRecord::Base

  validates :name, :presence => true
  validates  :url, :presence => true

  has_many :events, :dependent => :destroy
  
  def import
    updated = created = 0
    cal_string = open(url).read

    open(url) do |f|
      
      calendars = RiCal.parse(f)
      calendars.each do |cal|
    
        cal.events.each do |event|
          pending_event = extract_event_properties_rical(event)
          existing_event = events.find_by_uid(pending_event[:uid])
          if existing_event
            existing_event.update_attributes(pending_event)
            updated += 1
          else
            events.create(pending_event)
            created += 1
          end
        end
      end
    end
    logger.info "import result: created #{created} events, updated #{updated} events."
  end

private 
  def extract_event_properties(props)
    {
      :label => props['summary'],
      :at => props['dtstart'],
      :until => props['dtend'],
      :description => props['description'],
      :location => props['location'],
      :last_modified => props['last_modified'],
      :url => props['url'].to_s,
      :uid => props['uid'],
      :summary => props['summary']
    }
  end    

  def extract_event_properties_rical(event)
    {
      :label => event.summary,
      :at => event.dtstart,
      :until => event.dtend,
      :description => event.description,
      :location => event.location,
      :last_modified => event.last_modified,
      :url => event.url.to_s,
      :uid => event.uid,
      :summary => event.summary
    }
  end    



end

app/models/clipping.rb
class Clipping < ActiveRecord::Base
  belongs_to :source
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :calendar_feed

  scope :upcoming, where('at >= ?', Time.now()).order('at').limit(10)
  default_scope where('at >= ?', Time.now).order('at')
end

app/models/related_resource.rb
class RelatedResource < ActiveRecord::Base
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :clippings, :dependent => :destroy

  def import
    updated = created = 0
    feed = Feedzirra::Feed.fetch_and_parse feed_url
    feed.entries.each do |e|
      entry = Clipping.find_by_url(e.url)
      unless entry
        clippings.create(extract_entry_properties(e))
        created += 1
      end
    end
    logger.info "import result: created #{created} clippings."
  end

  def extract_entry_properties(entry)
    {
      :title => entry.title,
      :url => entry.url,
      :author => entry.author,
      :summary => entry.summary,
      :content => entry.content,
      :published => entry.published
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
    
  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?

  def require_admin
    unless current_user && current_user.admin?
      # TODO: raise exception?
      head :status => 404
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/calendars_controller.rb
class CalendarsController < InheritedResources::Base


end

app/controllers/clippings_controller.rb
class ClippingsController < InheritedResources::Base

end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base



end

app/controllers/source_controller.rb
class SourceController < ApplicationController
end

app/views/calendars/_form.html.haml
= form_for(@calendar) do |f|
  - if @calendar.errors.any?
    .error_explanation
      %h2
        = pluralize(@calendar.errors.count, 'error')
        prohibited this calendar from being saved:

      %ul
      - @calendar.errors.full_messages.each do |msg|
        %li= msg

  .actions
    = f.submit

app/views/clippings/_clipping.html.haml
.title
  = link_to clipping.title, clipping.url
.summary
  = clipping.summary.html_safe

app/views/events/_event.html.haml
%li.event
  .title
    = link_to event.label, event.url
  .date
    = event.at.strftime("%B %d, %l:%M %P")
  .location
    = event.location
  .links
    = link_to "more &raquo;".html_safe, url_for(event)

app/views/events/index.html.haml
%h1 Upcoming Events

%ul
  = render @events

app/views/events/show.html.haml
.event

  %h1.title= link_to @event.label, @event.url

  %h2.date
    = @event.at.strftime("%B %d, %l:%M %P")
  .location
    = @event.location
  .description
    = @event.description

app/views/front/_clippings.html.haml
h2 Boo
= render @clippings

app/views/front/_events.html.haml
.featured
  = render 'featured_event', :event => @events.shift if @events.shift
.upcoming
  = render @events

app/views/front/_featured_clip.html.haml
%h1 The Title
.clip
  Aliquam eget aliquam nulla. Pellentesque consequat elit id metus convallis et interdum leo commodo. Nullam adipiscing faucibus quam, sed sollicitudin augue vestibulum at. Curabitur aliquet nulla quis magna vehicula consequat. Donec sapien sapien, mollis eu malesuada at, tristique et dui. Nullam feugiat dictum felis, vel iaculis mi vehicula eget. Donec suscipit auctor arcu, eu luctus sapien vulputate eget. Vestibulum scelerisque consectetur porttitor. Nunc tellus diam, imperdiet dictum varius at, hendrerit et tellus. Mauris tempus sollicitudin nisi, vitae accumsan.
.source
  = link_to "more &raquo;".html_safe

app/views/front/_featured_event.html.haml
%li.event
  .title
    = link_to event.label, event_url(event)
  .date
    = event.at.strftime("%B %d, %l:%M %P")
  .location
    = event.location
  .description
    = event.description 
  .links
    = link_to "more &raquo;".html_safe, url_for(event)

app/views/front/_resources.html.haml
%ul
  = render @resources

app/views/front/index.html.haml
%section.splash
  %h1 Hubbubbly Presents:
  .featured
    = render 'featured_clip'
%section.clippings
  = render 'clippings'
%section.events
  = render 'events'
%section.resources
  = render 'resources'
.clearfix
  &nbsp;

app/views/identities/new.haml
= form_tag "/auth/identity/register" do
  - if @identity && @identity.errors.any?
    .error_messages
      %h2
        = pluralize(@identity.errors.count, "error")
        prohibited this account from being saved:
      %ul
        - @identity.errors.full_messages.each do |msg|
          %li= msg
  .field
    = label_tag :name
    %br
      = text_field_tag :name, @identity.try(:name)
  .field
    = label_tag :email
    %br
      = text_field_tag :email, @identity.try(:email)
  .field
    = label_tag :password
    %br
      = password_field_tag :password
  .field
    = label_tag :password_confirmation
    %br
      = password_field_tag :password_confirmation
  .actions= submit_tag "Register"

app/views/layouts/application.html.haml
!!!html

%html
  %head
    - page_title = yield(:page_title)
    %title #{page_title.present? ? page_title : "Keep Yourself in the Loop"} | Hubbubbly

    = csrf_meta_tag
    = javascript_include_tag :application
    = stylesheet_link_tag 'application'
    = yield :head
  
  %body
    .wrapper
      .registration
        - if user_signed_in?
          %li
            =# link_to('Edit registration', edit_user_registration_path)
        - else
          %li
            =# link_to('Register', new_user_registration_path)
      .login
        - if user_signed_in?
          %li
            = link_to 'Sign Out', signout_path, :method => :delete
        - else
          %li
            = link_to 'Sign In', signin_path
      .navigation
      .header
      
        = content_tag :p, flash[:error], :class=>"error" if flash[:error]
        = content_tag :p, flash[:notice], :class=>"notice" if flash[:notice] 
        = content_tag :p, flash[:alert], :class=>"error" if flash[:alert]

      .content      
        = yield 
  
      .footer
        .contact
          = link_to 'hubbubbly.com', 'hubbubbly.com'
          a charlotte, nc company<br/>
        .links
          = link_to 'about us', 'about'
          = link_to 'halp!', 'halp'
        .copyright
          &copy; 2010, hububbly, llc

app/views/layouts/manage.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Management Console | Start Charlotte</title>
  <%= stylesheet_link_tag 'styles' -%>
  <script src="http://www.google.com/jsapi" type="text/javascript"></script>
  <script type="text/javascript">
    google.load("jquery", "1.3.2");
  </script>
</head>

<body id="manage">
  <div id="wrapper">
    <div id="login">
      <div class="links">
        <%= link_to "Home", root_url%>
      </div>
      
      <%= pluralize User.logged_in.count, "user" %> currently logged in // 
      <% if !current_user %>
        <%= link_to "Register", new_account_path %> |
        <%= link_to "Log In", new_user_session_path %> 
      <% else %>
        <%= link_to "My Account", account_path %> |
        <%= link_to "Logout", user_session_path, :method => :delete, :confirm => "Are you sure you want to logout?" %>
        <%= link_to "Manage", manage_index_path if current_user.in_role?('admin') -%>
      <% end %>
    </div>
    <div id="header">
      <h1>hubbubbly: your interests, your area</h1>
    </div>
    
    <%= content_tag :p, flash[:notice], :class=>"notice" -%>
    <%= content_tag :p, flash[:error], :class=>"error" -%>

  <div class="manage-sidebar">
    <ul>
      <li><%= link_to 'Manage Home', manage_index_path -%></li>
      <li><%= link_to 'Communities', manage_communities_path %></li>
      <li><%= link_to 'Feeds', manage_feeds_path %></li>
    </ul>  
  </div>

  <div class="content">
  <%= yield %>
  <div style="clear:both;"></div>
  </div>  
  <div id="footer">
    <div class="contact">
      <%= link_to 'hubbubbly.com', 'hubbubbly.com' -%><br/>
      a charlotte, nc company<br/>
    </div>
    <div class="links">
      <%= link_to 'about us', 'about'-%><br/>
      <%= link_to 'halp!', 'halp' -%>
    </div>
  <div style="clear:both;"></div>
  </div>
  <div id='copyright'>
    &copy; 2010, hububbly, llc
  </div>
  
  </div>
</body>
</html>

app/views/related_resources/_related_resource.html.haml
%li= link_to related_resource.name, related_resource.url

app/views/shared/_avatar.html.erb
<img class="avatar" src="<%= avatar.url(:medium) %>">

app/views/shared/_feed_item.html.erb
<div class="item">
  <h3><%= link_to feed_item.title, feed_item.link -%></h3>
  <%= content_tag :p, feed_item.description unless feed_item.description.strip.blank? -%>
</div>

app/views/shared/_follow.html.erb
CURRENT USER:<%= current_user.email%>
CAN FOLLOW:<%= current_user.can_follow?(user)%>
<% if current_user && current_user.can_follow?(user) %>

  <% form_for Follow.new(:follower => current_user, :followable => user) do |f| %>
    <%= f.error_messages %>
    <%= f.hidden_field :follower_id %>
    <%= f.hidden_field :followable_type %>
    <%= f.hidden_field :followable_id %>
    <span>
      <%= f.submit 'Follow' %>
    </span>
  <% end %>
<% elsif current_user && current_user.follows?(user) %>
  <% form_for current_user.follow_for(user), :html => {:method => :delete} do |f| %>
    <%= f.error_messages %>
    <%= f.hidden_field :follower_id %>
    <%= f.hidden_field :followable_type %>
    <%= f.hidden_field :followable_id %>
    <span>
      <%= f.submit 'Unfollow' %>
    </span>
  <% end %>
<% else %>
  <%# raise "ASPLODE!"%>
<% end %>

app/views/site/home.html.erb
<div id="splash">
  <%= avatars_for(@users) %>
</div>
<div id="events">
  <h2>Upcoming Events</h2>
  <div class="event" id="event-1233">
    <div class="datetime">Friday May 15 @ 6.5p</div>
    <div class="title">Startup Weekend!</div>
    <div class="location">Enventys, Inc.</div>
  </div>  

  <div class="event" id="event-1234">
    <div class="datetime">Thursday May 20 @ 6.5p</div>
    <div class="title">Introduction to WebSockets</div>
    <div class="location">AREA 15 in Charlotte, NC</div>
  </div>  
  <div class="event" id="event-1235">
    <div class="datetime">Tuesday June 22 @ 7p</div>
    <div class="title">Ruby 1 oh 1</div>
    <div class="location">AREA 15 in Charlotte, NC</div>
  </div>  
  <div class="event" id="event-1236">
    <div class="datetime">Monday, June 4 @ 8a</div>
    <div class="title">RAILSCONF</div>
    <div class="location">Baltimore, MD</div>
  </div>  
  <br/><%= link_to "See All >>", '#', :class => 'right-on'-%>
  
</div>
<div id="items">
  <h2>Latest Posts</h2>
  <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  <br/><%= link_to "More >>", feed_items_path, :class => 'right-on'-%>
</div>
<div id="chatter">
  <h2>Chatter</h2>
  <div class="chat">
    <span class="from">@bigfleet:</span> 
    Juggalos invading the codebase! Thanks a lot, last.fm recommended events!
    <br/>5 minutes ago via Tweetie
  </div>
  <div class="chat">
    <span class="from">@Ryan_Burkhart:</span> 
    @SummerPlum Doh! However, sometimes it's not what you do (cause, it's all been done before) - It's the attitude you do it with!    <br/>5 minutes ago via Tweetie
    <br/>6 minutes ago via web in reply to SummerPlum
  </div>
  <div class="chat">
    <span class="from">@SummerPlum:</span> 
    @Ryan_Burkhart this is why you do market research...    
    <br/>7 minutes ago via Tweetie
  </div>
  <div class="chat">
    <span class="from">@jasonfried:</span> 
    The biggest school in the world is run (and taught) by one guy: <%= link_to 'http://vimeo.com/11731351', 'http://vimeo.com/11731351' -%>    
    <br/>8 minutes ago via web  
  </div>  
</div>